version: '3.8'

networks:
  crdp-cassandra-net:
    driver: bridge

services:
  zookeeper:
    image: zookeeper:latest
    container_name: zookeeper
    networks:
      - crdp-cassandra-net
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
    ports:
      - "2181:2181"
    healthcheck:
      test: ["CMD", "echo", "ruok", "|", "nc", "-w", "2", "localhost", "2181"]
      interval: 10s
      timeout: 5s
      retries: 3

  kafka-broker:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-broker
    networks:
      - crdp-cassandra-net
    depends_on:
      zookeeper:
        condition: service_healthy
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka-broker:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    ports:
      - "9092:9092"
    healthcheck:
      test: ["CMD", "/usr/bin/kafka-topics", "--list", "--bootstrap-server", "localhost:9092"]
      interval: 10s
      timeout: 5s
      retries: 3

  kafka-topic-creator:
    image: confluentinc/cp-kafka:latest
    networks:
      - crdp-cassandra-net
    depends_on:
      kafka-broker:
        condition: service_healthy
    command: >
      bash -c "sleep 10 && for region in jakarta nyc london sydney saopaulo; do
        /usr/bin/kafka-topics --create \
        --bootstrap-server kafka-broker:9092 \
        --replication-factor 1 \
        --partitions 2 \
        --topic crdp-sensors-\$${region} || true;
      done"

  # Cassandra nodes (3 nodes per region * 5 regions = 15 nodes)
  cassandra-jakarta-1:
    image: cassandra:latest
    container_name: cassandra-jakarta-1
    networks:
      - crdp-cassandra-net
    environment:
      - CASSANDRA_CLUSTER_NAME=CRDPCluster
      - CASSANDRA_DC=Jakarta
      - CASSANDRA_RACK=Rack1
      - CASSANDRA_SEEDS=cassandra-jakarta-1
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
      - JVM_OPTS=-Dcom.sun.management.jmxremote.port=7199 -Dcom.sun.management.jmxremote.rmi.port=7199 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Djava.rmi.server.hostname=172.21.0.2 -XX:MaxDirectMemorySize=512M
    ports:
      - "9042:9042"
      - "7199:7199"
    volumes:
      - cassandra-jakarta-1-data:/var/lib/cassandra

  cassandra-jakarta-2:
    image: cassandra:latest
    container_name: cassandra-jakarta-2
    networks:
      - crdp-cassandra-net
    environment:
      - CASSANDRA_CLUSTER_NAME=CRDPCluster
      - CASSANDRA_DC=Jakarta
      - CASSANDRA_RACK=Rack1
      - CASSANDRA_SEEDS=cassandra-jakarta-1
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
      - JVM_OPTS=-Dcom.sun.management.jmxremote.port=7199 -Dcom.sun.management.jmxremote.rmi.port=7199 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Djava.rmi.server.hostname=172.21.0.3 -XX:MaxDirectMemorySize=512M
    ports:
      - "9043:9042"
      - "7200:7199"
    volumes:
      - cassandra-jakarta-2-data:/var/lib/cassandra

  cassandra-jakarta-3:
    image: cassandra:latest
    container_name: cassandra-jakarta-3
    networks:
      - crdp-cassandra-net
    environment:
      - CASSANDRA_CLUSTER_NAME=CRDPCluster
      - CASSANDRA_DC=Jakarta
      - CASSANDRA_RACK=Rack1
      - CASSANDRA_SEEDS=cassandra-jakarta-1
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
      - JVM_OPTS=-Dcom.sun.management.jmxremote.port=7199 -Dcom.sun.management.jmxremote.rmi.port=7199 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Djava.rmi.server.hostname=172.21.0.4 -XX:MaxDirectMemorySize=512M
    ports:
      - "9044:9042"
      - "7201:7199"
    volumes:
      - cassandra-jakarta-3-data:/var/lib/cassandra

  cassandra-nyc-1:
    image: cassandra:latest
    container_name: cassandra-nyc-1
    networks:
      - crdp-cassandra-net
    environment:
      - CASSANDRA_CLUSTER_NAME=CRDPCluster
      - CASSANDRA_DC=NYC
      - CASSANDRA_RACK=Rack1
      - CASSANDRA_SEEDS=cassandra-jakarta-1
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
      - JVM_OPTS=-Dcom.sun.management.jmxremote.port=7199 -Dcom.sun.management.jmxremote.rmi.port=7199 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Djava.rmi.server.hostname=172.21.0.5 -XX:MaxDirectMemorySize=512M
    ports:
      - "9045:9042"
      - "7202:7199"
    volumes:
      - cassandra-nyc-1-data:/var/lib/cassandra

  cassandra-nyc-2:
    image: cassandra:latest
    container_name: cassandra-nyc-2
    networks:
      - crdp-cassandra-net
    environment:
      - CASSANDRA_CLUSTER_NAME=CRDPCluster
      - CASSANDRA_DC=NYC
      - CASSANDRA_RACK=Rack1
      - CASSANDRA_SEEDS=cassandra-jakarta-1
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
      - JVM_OPTS=-Dcom.sun.management.jmxremote.port=7199 -Dcom.sun.management.jmxremote.rmi.port=7199 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Djava.rmi.server.hostname=172.21.0.6 -XX:MaxDirectMemorySize=512M
    ports:
      - "9046:9042"
      - "7203:7199"
    volumes:
      - cassandra-nyc-2-data:/var/lib/cassandra

  cassandra-nyc-3:
    image: cassandra:latest
    container_name: cassandra-nyc-3
    networks:
      - crdp-cassandra-net
    environment:
      - CASSANDRA_CLUSTER_NAME=CRDPCluster
      - CASSANDRA_DC=NYC
      - CASSANDRA_RACK=Rack1
      - CASSANDRA_SEEDS=cassandra-jakarta-1
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
      - JVM_OPTS=-Dcom.sun.management.jmxremote.port=7199 -Dcom.sun.management.jmxremote.rmi.port=7199 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Djava.rmi.server.hostname=172.21.0.7 -XX:MaxDirectMemorySize=512M
    ports:
      - "9047:9042"
      - "7204:7199"
    volumes:
      - cassandra-nyc-3-data:/var/lib/cassandra

  cassandra-london-1:
    image: cassandra:latest
    container_name: cassandra-london-1
    networks:
      - crdp-cassandra-net
    environment:
      - CASSANDRA_CLUSTER_NAME=CRDPCluster
      - CASSANDRA_DC=London
      - CASSANDRA_RACK=Rack1
      - CASSANDRA_SEEDS=cassandra-jakarta-1
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
      - JVM_OPTS=-Dcom.sun.management.jmxremote.port=7199 -Dcom.sun.management.jmxremote.rmi.port=7199 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Djava.rmi.server.hostname=172.21.0.8 -XX:MaxDirectMemorySize=512M
    ports:
      - "9048:9042"
      - "7205:7199"
    volumes:
      - cassandra-london-1-data:/var/lib/cassandra

  cassandra-london-2:
    image: cassandra:latest
    container_name: cassandra-london-2
    networks:
      - crdp-cassandra-net
    environment:
      - CASSANDRA_CLUSTER_NAME=CRDPCluster
      - CASSANDRA_DC=London
      - CASSANDRA_RACK=Rack1
      - CASSANDRA_SEEDS=cassandra-jakarta-1
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
      - JVM_OPTS=-Dcom.sun.management.jmxremote.port=7199 -Dcom.sun.management.jmxremote.rmi.port=7199 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Djava.rmi.server.hostname=172.21.0.9 -XX:MaxDirectMemorySize=512M
    ports:
      - "9049:9042"
      - "7206:7199"
    volumes:
      - cassandra-london-2-data:/var/lib/cassandra

  cassandra-london-3:
    image: cassandra:latest
    container_name: cassandra-london-3
    networks:
      - crdp-cassandra-net
    environment:
      - CASSANDRA_CLUSTER_NAME=CRDPCluster
      - CASSANDRA_DC=London
      - CASSANDRA_RACK=Rack1
      - CASSANDRA_SEEDS=cassandra-jakarta-1
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
      - JVM_OPTS=-Dcom.sun.management.jmxremote.port=7199 -Dcom.sun.management.jmxremote.rmi.port=7199 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Djava.rmi.server.hostname=172.21.0.10 -XX:MaxDirectMemorySize=512M
    ports:
      - "9050:9042"
      - "7207:7199"
    volumes:
      - cassandra-london-3-data:/var/lib/cassandra

  cassandra-sydney-1:
    image: cassandra:latest
    container_name: cassandra-sydney-1
    networks:
      - crdp-cassandra-net
    environment:
      - CASSANDRA_CLUSTER_NAME=CRDPCluster
      - CASSANDRA_DC=Sydney
      - CASSANDRA_RACK=Rack1
      - CASSANDRA_SEEDS=cassandra-jakarta-1
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
      - JVM_OPTS=-Dcom.sun.management.jmxremote.port=7199 -Dcom.sun.management.jmxremote.rmi.port=7199 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Djava.rmi.server.hostname=172.21.0.11 -XX:MaxDirectMemorySize=512M
    ports:
      - "9051:9042"
      - "7208:7199"
    volumes:
      - cassandra-sydney-1-data:/var/lib/cassandra

  cassandra-sydney-2:
    image: cassandra:latest
    container_name: cassandra-sydney-2
    networks:
      - crdp-cassandra-net
    environment:
      - CASSANDRA_CLUSTER_NAME=CRDPCluster
      - CASSANDRA_DC=Sydney
      - CASSANDRA_RACK=Rack1
      - CASSANDRA_SEEDS=cassandra-jakarta-1
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
      - JVM_OPTS=-Dcom.sun.management.jmxremote.port=7199 -Dcom.sun.management.jmxremote.rmi.port=7199 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Djava.rmi.server.hostname=172.21.0.12 -XX:MaxDirectMemorySize=512M
    ports:
      - "9052:9042"
      - "7209:7199"
    volumes:
      - cassandra-sydney-2-data:/var/lib/cassandra

  cassandra-sydney-3:
    image: cassandra:latest
    container_name: cassandra-sydney-3
    networks:
      - crdp-cassandra-net
    environment:
      - CASSANDRA_CLUSTER_NAME=CRDPCluster
      - CASSANDRA_DC=Sydney
      - CASSANDRA_RACK=Rack1
      - CASSANDRA_SEEDS=cassandra-jakarta-1
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
      - JVM_OPTS=-Dcom.sun.management.jmxremote.port=7199 -Dcom.sun.management.jmxremote.rmi.port=7199 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Djava.rmi.server.hostname=172.21.0.13 -XX:MaxDirectMemorySize=512M
    ports:
      - "9053:9042"
      - "7210:7199"
    volumes:
      - cassandra-sydney-3-data:/var/lib/cassandra

  cassandra-saopaulo-1:
    image: cassandra:latest
    container_name: cassandra-saopaulo-1
    networks:
      - crdp-cassandra-net
    environment:
      - CASSANDRA_CLUSTER_NAME=CRDPCluster
      - CASSANDRA_DC=SaoPaulo
      - CASSANDRA_RACK=Rack1
      - CASSANDRA_SEEDS=cassandra-jakarta-1
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
      - JVM_OPTS=-Dcom.sun.management.jmxremote.port=7199 -Dcom.sun.management.jmxremote.rmi.port=7199 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Djava.rmi.server.hostname=172.21.0.14 -XX:MaxDirectMemorySize=512M
    ports:
      - "9054:9042"
      - "7211:7199"
    volumes:
      - cassandra-saopaulo-1-data:/var/lib/cassandra

  cassandra-saopaulo-2:
    image: cassandra:latest
    container_name: cassandra-saopaulo-2
    networks:
      - crdp-cassandra-net
    environment:
      - CASSANDRA_CLUSTER_NAME=CRDPCluster
      - CASSANDRA_DC=SaoPaulo
      - CASSANDRA_RACK=Rack1
      - CASSANDRA_SEEDS=cassandra-jakarta-1
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
      - JVM_OPTS=-Dcom.sun.management.jmxremote.port=7199 -Dcom.sun.management.jmxremote.rmi.port=7199 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Djava.rmi.server.hostname=172.21.0.15 -XX:MaxDirectMemorySize=512M
    ports:
      - "9055:9042"
      - "7212:7199"
    volumes:
      - cassandra-saopaulo-2-data:/var/lib/cassandra

  cassandra-saopaulo-3:
    image: cassandra:latest
    container_name: cassandra-saopaulo-3
    networks:
      - crdp-cassandra-net
    environment:
      - CASSANDRA_CLUSTER_NAME=CRDPCluster
      - CASSANDRA_DC=SaoPaulo
      - CASSANDRA_RACK=Rack1
      - CASSANDRA_SEEDS=cassandra-jakarta-1
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
      - JVM_OPTS=-Dcom.sun.management.jmxremote.port=7199 -Dcom.sun.management.jmxremote.rmi.port=7199 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Djava.rmi.server.hostname=172.21.0.16 -XX:MaxDirectMemorySize=512M
    ports:
      - "9056:9042"
      - "7213:7199"
    volumes:
      - cassandra-saopaulo-3-data:/var/lib/cassandra

  # Spark cluster (1 master + 3 workers)
  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    networks:
      - crdp-cassandra-net
    command: /opt/bitnami/spark/bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "8080:8080"
      - "7077:7077"

  spark-worker-1:
    image: bitnami/spark:latest
    container_name: spark-worker-1
    networks:
      - crdp-cassandra-net
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    command: /opt/bitnami/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077

  spark-worker-2:
    image: bitnami/spark:latest
    container_name: spark-worker-2
    networks:
      - crdp-cassandra-net
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    command: /opt/bitnami/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077

  spark-worker-3:
    image: bitnami/spark:latest
    container_name: spark-worker-3
    networks:
      - crdp-cassandra-net
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    command: /opt/bitnami/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077

  # Airflow
  airflow:
    image: apache/airflow:2.7.0
    container_name: airflow
    networks:
      - crdp-cassandra-net
    command: airflow-standalone
    ports:
      - "8081:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags

  # Prometheus
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    networks:
      - crdp-cassandra-net
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  # Grafana
  grafana:
    image: grafana/grafana
    container_name: grafana
    networks:
      - crdp-cassandra-net
    ports:
      - "3000:3000"

volumes:
  cassandra-jakarta-1-data:
  cassandra-jakarta-2-data:
  cassandra-jakarta-3-data:
  cassandra-nyc-1-data:
  cassandra-nyc-2-data:
  cassandra-nyc-3-data:
  cassandra-london-1-data:
  cassandra-london-2-data:
  cassandra-london-3-data:
  cassandra-sydney-1-data:
  cassandra-sydney-2-data:
  cassandra-sydney-3-data:
  cassandra-saopaulo-1-data:
  cassandra-saopaulo-2-data:
  cassandra-saopaulo-3-data: