global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'cassandra'
    static_configs:
      - targets: ['cassandra:9042']
  - job_name: 'spark'
    static_configs:
      - targets: ['spark-master:8080']
